version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
    - location: scripts/project_clean.sh
      timeout: 300
      runas: root  
      
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/project_deploy.sh
      timeout: 300
      runas: root
    - location: scripts/project_copy_war.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
