version: 0.0
os: linux
files:
  - source: /src
    destination: /home/ubuntu/deploy

hooks:

  BeforeInstall:
    - location: scripts/project_deploy.sh
    - location: scripts/project_copy_war.sh

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start_server.sh
